<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsim</string>
	</array>
	<key>name</key>
	<string>JSim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Commented out lines</string>
			<key>match</key>
			<string>\*.+$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.include.c</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\.include\s+(.*)</string>
			<key>name</key>
			<string>keyword.control.import.include.c</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\.subckt\s+([A-Za-z]+)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.ends$</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(^[xX]\w+)\b.*\b(.+)$</string>
			<key>name</key>
			<string>source</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jsim</string>
	<key>uuid</key>
	<string>13be1add-80c1-4aab-b81b-b6ab60a0ecda</string>
</dict>
</plist>
